import { LUT_PRESETS } from '../utils/proceduralLUT';
import type { RenderDebugSettings } from './gameStore';

export const DEFAULT_RENDER_DEBUG: RenderDebugSettings = {
  showDevPanel: false,
  minimap: true,
  shadows: true,
  postprocessing: true,
  bloom: true,
  vignette: true,
  ao: false,
  brightnessContrast: true,
  hueSaturation: true,
  lutEnabled: false,
  lutPreset: 'tropical',
  lutParams: { ...LUT_PRESETS.tropical },
  lutMode: 'auto',
  advancedWater: true,
  shipWake: true,
  rain: false,
  algae: true,
  coralReefs: false,
  reefCaustics: false,
  wildlifeMotion: true,
  cloudShadows: true,
  cityGroundWear: true,
  animalMarkers: true,
  disableTransitions: false,
  cityFieldOverlay: false,
  cityFieldMode: 'prestige',
  sacredMarkers: true,
  poiBeacons: true,
  poiVisibility: true,
};
