import type { Nationality, CulturalRegion } from './gameStore';

// Map port IDs to their controlling nationality for reputation.
export const PORT_FACTION: Record<string, Nationality> = {
  calicut: 'Gujarati',
  goa: 'Portuguese',
  hormuz: 'Portuguese',
  malacca: 'Portuguese',
  aden: 'Ottoman',
  mocha: 'Ottoman',
  zanzibar: 'Swahili',
  macau: 'Portuguese',
  mombasa: 'Portuguese',
  surat: 'Mughal',
  muscat: 'Portuguese',
  bantam: 'Javanese',
  manila: 'Spanish',
  nagasaki: 'Japanese',
  masulipatnam: 'Mughal',
  socotra: 'Omani',
  diu: 'Portuguese',
  lisbon: 'Portuguese',
  amsterdam: 'Dutch',
  seville: 'Spanish',
  london: 'English',
  venice: 'Venetian',
  elmina: 'Portuguese',
  luanda: 'Portuguese',
  salvador: 'Portuguese',
  havana: 'Spanish',
  cartagena: 'Spanish',
  veracruz: 'Spanish',
  jamestown: 'English',
  colombo: 'Portuguese',
  cape: 'Khoikhoi',
};

// Cultural region of the built environment, separate from controlling nationality.
export const PORT_CULTURAL_REGION: Record<string, CulturalRegion> = {
  aden: 'Arab',
  hormuz: 'Arab',
  muscat: 'Arab',
  socotra: 'Arab',
  mombasa: 'Swahili',
  zanzibar: 'Swahili',
  surat: 'Gujarati',
  diu: 'Gujarati',
  masulipatnam: 'Gujarati',
  colombo: 'Malabari',
  calicut: 'Malabari',
  goa: 'Malabari',
  malacca: 'Malay',
  bantam: 'Malay',
  macau: 'Chinese',
};
